import os
import time
import json
import asyncio
import threading
from collections import deque
from datetime import datetime
from typing import List, Dict, Any

from prometheus_client import Counter, generate_latest
from aiohttp import web
from config import config_instance

# Prometheus Counters
LLM_USAGE_INPUT = Counter("llm_usage_input", "Total input tokens sent to LLM", ["model", "chat", "function"])
LLM_USAGE_INPUT_CACHE_HIT = Counter("llm_usage_input_cache_hit", "Input tokens served from prompt cache", ["model", "chat", "function"])
LLM_USAGE_INPUT_CACHE_MISS = Counter("llm_usage_input_cache_miss", "Input tokens that missed prompt cache", ["model", "chat", "function"])
LLM_USAGE_OUTPUT = Counter("llm_usage_output", "Total output tokens generated by LLM", ["model", "chat", "function"])

# Real-time log buffer (stores last 500 logs in memory)
MAX_LOGS = 500
log_buffer = deque(maxlen=MAX_LOGS)
log_subscribers = set()
_web_loop = None

def _broadcast_entry(entry: dict):
    dead_subscribers = set()
    for queue in list(log_subscribers):
        try:
            queue.put_nowait(entry)
        except Exception:
            dead_subscribers.add(queue)
    for dead in dead_subscribers:
        log_subscribers.discard(dead)

def log_event(category: str, text: str):
    """
    Logs an event to console and broadcasts to real-time web UI dashboard.
    """
    now_str = datetime.now().strftime("%H:%M:%S")
    entry = {
        "id": int(time.time() * 1000),
        "time": now_str,
        "category": category,
        "text": text
    }
    log_buffer.append(entry)
    print(f"[{now_str}] [{category}] {text}")

    # Broadcast thread-safely to web event loop
    global _web_loop
    if _web_loop and _web_loop.is_running():
        _web_loop.call_soon_threadsafe(_broadcast_entry, entry)

def track_llm_usage(model: str, input_tokens: int, output_tokens: int, cache_hit: int = 0, chat: str = "general", function: str = "chat"):
    model = model or "unknown"
    chat = chat or "general"
    function = function or "chat"
    cache_miss = max(0, input_tokens - cache_hit)
    
    LLM_USAGE_INPUT.labels(model=model, chat=chat, function=function).inc(input_tokens)
    LLM_USAGE_OUTPUT.labels(model=model, chat=chat, function=function).inc(output_tokens)
    if cache_hit > 0:
        LLM_USAGE_INPUT_CACHE_HIT.labels(model=model, chat=chat, function=function).inc(cache_hit)
    if cache_miss > 0:
        LLM_USAGE_INPUT_CACHE_MISS.labels(model=model, chat=chat, function=function).inc(cache_miss)

    log_event("METRICS", f"[{function}] Model: {model} | In: {input_tokens} tokens | Out: {output_tokens} tokens")

# HTML Dashboard for Real-time Logs & Metrics
LOGS_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Kuni AI - Real-time Logs & Metrics Dashboard</title>
    <style>
        body {
            background-color: #0f172a;
            color: #e2e8f0;
            font-family: 'JetBrains Mono', monospace, Consolas, sans-serif;
            margin: 0;
            padding: 20px;
        }
        h1 {
            color: #38bdf8;
            margin-bottom: 5px;
            font-size: 24px;
        }
        .subtitle {
            color: #94a3b8;
            font-size: 13px;
            margin-bottom: 20px;
        }
        .nav {
            display: flex;
            gap: 10px;
            margin-bottom: 15px;
        }
        .nav button {
            background: #1e293b;
            border: 1px solid #334155;
            color: #f1f5f9;
            padding: 8px 16px;
            border-radius: 6px;
            cursor: pointer;
            font-weight: bold;
        }
        .nav button.active {
            background: #0284c7;
            border-color: #38bdf8;
        }
        #log-container {
            background: #020617;
            border: 1px solid #1e293b;
            border-radius: 8px;
            padding: 15px;
            height: 70vh;
            overflow-y: auto;
            font-size: 13px;
            line-height: 1.5;
        }
        .log-entry {
            margin-bottom: 6px;
            border-bottom: 1px solid #0f172a;
            padding-bottom: 4px;
            word-wrap: break-word;
        }
        .time { color: #64748b; }
        .cat-BOT { color: #a855f7; font-weight: bold; }
        .cat-AI { color: #38bdf8; font-weight: bold; }
        .cat-METRICS { color: #22c55e; font-weight: bold; }
        .cat-SYSTEM { color: #eab308; font-weight: bold; }
        .cat-PROXY { color: #ec4899; font-weight: bold; }
        .cat-PROXY_TOOL { color: #f43f5e; font-weight: bold; }
    </style>
</head>
<body>
    <h1>Kuni AI Dashboard</h1>
    <div class="subtitle">Live Real-time Log Stream & Prometheus Metrics Exporter (Port 9464)</div>

    <div class="nav">
        <button id="btn-logs" class="active" onclick="showTab('logs')">Live Bot & AI Logs</button>
        <button id="btn-metrics" onclick="showTab('metrics')">Raw Prometheus Metrics</button>
    </div>

    <div id="logs-tab">
        <div id="log-container"></div>
    </div>

    <div id="metrics-tab" style="display:none;">
        <iframe id="metrics-frame" style="width:100%; height:70vh; background:#020617; border:1px solid #1e293b; border-radius:8px;"></iframe>
    </div>

    <script>
        const container = document.getElementById('log-container');
        const seenIds = new Set();

        function appendLog(log) {
            if (log.id && seenIds.has(log.id)) return;
            if (log.id) seenIds.add(log.id);

            const div = document.createElement('div');
            div.className = 'log-entry';
            const catClass = 'cat-' + (log.category || 'BOT').toUpperCase().replace(/[^A-Z]/g, '');
            div.innerHTML = `<span class="time">[${log.time}]</span> <span class="${catClass}">[${log.category}]</span> ${escapeHtml(log.text)}`;
            container.appendChild(div);
            container.scrollTop = container.scrollHeight;
        }

        function escapeHtml(text) {
            return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
        }

        function showTab(tab) {
            if (tab === 'logs') {
                document.getElementById('logs-tab').style.display = 'block';
                document.getElementById('metrics-tab').style.display = 'none';
                document.getElementById('btn-logs').className = 'active';
                document.getElementById('btn-metrics').className = '';
            } else {
                document.getElementById('logs-tab').style.display = 'none';
                document.getElementById('metrics-tab').style.display = 'block';
                document.getElementById('btn-logs').className = '';
                document.getElementById('btn-metrics').className = 'active';
                document.getElementById('metrics-frame').src = '/metrics';
            }
        }

        function fetchLogs() {
            fetch('/api/logs/history')
                .then(res => res.json())
                .then(data => {
                    data.forEach(log => appendLog(log));
                }).catch(e => {});
        }

        fetchLogs();
        setInterval(fetchLogs, 1000); // 1-second real-time polling fallback

        try {
            const evtSource = new EventSource("/stream/logs");
            evtSource.onmessage = function(event) {
                const log = JSON.parse(event.data);
                appendLog(log);
            };
        } catch(e) {}
    </script>
</body>
</html>
"""

async def handle_index(request):
    return web.Response(text=LOGS_HTML, content_type='text/html')

async def handle_metrics(request):
    data = generate_latest()
    return web.Response(body=data, content_type="text/plain")

async def handle_logs_history(request):
    return web.json_response(list(log_buffer))

async def handle_logs_stream(request):
    response = web.StreamResponse(
        status=200,
        reason='OK',
        headers={
            'Content-Type': 'text/event-stream',
            'Cache-Control': 'no-cache',
            'Connection': 'keep-alive',
        }
    )
    await response.prepare(request)

    queue = asyncio.Queue()
    log_subscribers.add(queue)

    try:
        while True:
            log_entry = await queue.get()
            data_str = f"data: {json.dumps(log_entry)}\n\n"
            await response.write(data_str.encode('utf-8'))
    except (asyncio.CancelledError, ConnectionResetError):
        pass
    finally:
        log_subscribers.discard(queue)

    return response

_server_started = False

def start_metrics_server():
    global _server_started
    if _server_started:
        return
    _server_started = True

    port = config_instance.get("general", "metrics_port", 9464)

    async def _run_app():
        global _web_loop
        _web_loop = asyncio.get_running_loop()

        app = web.Application()
        app.router.add_get('/', handle_index)
        app.router.add_get('/logs', handle_index)
        app.router.add_get('/metrics', handle_metrics)
        app.router.add_get('/api/logs/history', handle_logs_history)
        app.router.add_get('/stream/logs', handle_logs_stream)

        runner = web.AppRunner(app)
        await runner.setup()
        site = web.TCPSite(runner, '0.0.0.0', port)
        await site.start()
        print(f"[Metrics] Dashboard & Real-Time Logs Web Server running at http://localhost:{port}/")

    def _start_thread():
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        loop.run_until_complete(_run_app())
        loop.run_forever()

    t = threading.Thread(target=_start_thread, daemon=True)
    t.start()
